### ISSUE TITLE
RGBW bin file ?

### ISSUE THREAD

**Issue by rmuike** [AchimPieters/ESP8266-HomeKit-NeoPixel-Light-Strip#1]
hello, i´m trying to use a rgbw strip but no matter what bin file i use the colors are off. if i select any color the colors are all over the place each led has a different color .  

Do you have the correct bin file for RGBW strips ?

**Comment by AchimPieters** [comment]
You need a common ground! That wil fix it, it jas boring to do whith the code trad this fit more information: https://learn.adafruit.com/adafruit-neopixel-uberguide/overview

**Comment by rmuike** [comment]
You dont know you are talking about ! It has nothing to do with common ground !
